FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY monitor.py .
COPY production.py .
COPY production_fixed.py .
COPY production_naver.py .
COPY production_naver_live.py .
COPY production_naver_state.py .
COPY production_investing.py .
COPY production_v14.py .
COPY production_kpi100_mobile.py .
COPY production_v17.py .
COPY production_v18.py .
COPY production_v19.py .
COPY production_v20.py .
COPY production_v21.py .
COPY production_v22.py .
COPY production_v23.py .
COPY production_v24.py .
COPY production_v25.py .
COPY production_v26.py .
COPY production_v27.py .
COPY production_v28.py .
COPY production_v29.py .
COPY production_v30.py .
COPY execution_evidence_ledger.py .
COPY push_receipts.py .
COPY push_self_test.py .
COPY push_health.py .
COPY market_basis.py .
COPY corporate_action_registry.py .
COPY fx_basis.py .
COPY production_v31.py .
COPY production_v32.py .
COPY briefing.py .
COPY history_routes.py .
COPY laggards.py .
COPY next_day_probability.py .
COPY next_day_probability_v31.py .
COPY next_day_probability_v33.py .
COPY next_day_probability_v34.py .
COPY one_month_probability.py .
COPY one_month_distribution.py .
COPY one_month_calibrated.py .
COPY kospi_monthly.py .
COPY kospi_nextday_probability.py .
COPY extended_session_probability.py .
COPY extended_session_kospi_fallback.py .
COPY extended_market_display.py .
COPY probability_shadow.py .
COPY probability_milestone.py .
COPY probability_model.py .
COPY probability_model_v31_runtime.py .
COPY probability_model_v33_runtime.py .
COPY probability_model_v34_runtime.py .
COPY probability_v35_research.py .
COPY probability_v39_open_nowcast.py .
COPY probability_v40_firsthour.py .
COPY probability_v312_futures_preopen.py .
COPY preopen_futures_v312.py .
COPY preopen_futures_v312_live.py .
COPY open_nowcast_v39.py .
COPY firsthour_nowcast_v40.py .
COPY probability_live_gate.py .
COPY probability_live_gate_patch.py .
COPY probability_pipeline.py .
COPY sitecustomize.py .
ENV PYTHONPATH=/app
ENV PORT=8080
CMD ["sh", "-c", "python -m uvicorn production_v32:app --host 0.0.0.0 --port ${PORT:-8080}"]